### ISSUE TITLE
AWS elastic beanstalk files

### ISSUE THREAD

**Issue by zaro0508** [0xadada/dockdj#8]
Thanks for sharing this project.  I'm trying to setup something similar and looking at this project as an example.  I've read the [Deployment](https://github.com/0xadada/dockdj/wiki/Deployments) wiki which mentions elastic beanstalk files however I don't see any checked into this repository.  Was wondering whether that's on purpose or are all those EB files __not__ supposed to be checked in?  I guess I'm looking for examples.  If you could add some that would be great, if not then references to examples would help as well.

**Comment by 0xadada** [comment]
These files are generated by the Amazon `eb` CLI utility. You can see i've explicitly ignored these files from git, here:

https://github.com/0xadada/dockdj/blob/master/.gitignore#L34

I don't want them in the repo, because they could potentially vary from deploy to deploy, and even contain secrets.
